### ISSUE TITLE
iRate Component Crashes App (in Preview mode)

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/XamarinComponents#110]
Simply install into an application and you will get a crash when the app launches on iOS 10.2 when you set: 

iRate.Instance.PreviewMode = true;

Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[AppDelegate window]: unrecognized selector sent to instance 0x608000010710

I also assume that it will crash if it is in normal mode and wants to pop up a dialog. Assumption is dialog has been remove for whatever they are trying to open.

**Comment by yuriy-blinov** [comment]
Hi @jamesmontemagno,
I had the same issue with it today.
The simple workaround for it is to define public Window property in your AppDelegate class.

`		
    public override UIWindow Window => window;
`

Here is the line which causing this issue in the original Objective C code https://github.com/nicklockwood/iRate/blob/master/iRate/iRate.m:

`
    UIViewController *topController = [UIApplication sharedApplication].delegate.window.rootViewController;
`

It can be fixed by changing it to:

`
    UIViewController *topController = [UIApplication sharedApplication].keyWindow.rootViewController;
`

So maybe it makes sense to close this one and reopen it in https://github.com/nicklockwood/iRate project.

**Comment by Sebastian1989101** [comment]
Is there a updated planed to fix this problem? Actual it works with using "public override UIWindow Window => new UIWindow();" - but I don't know what kind of problems this brings with it.

**Comment by newky2k** [comment]
This project has been deprecated by the author and will not receive any further updates, also there have been newer versions in the last year which may fix them
