### ISSUE TITLE
Xamarn.FireBase.JobDispatcher dependency on other libraries?

### ISSUE THREAD

**Issue by mikevandre** [xamarin/XamarinComponents#159]
@topgenorth I am trying to get up and running with the JobDispatcher. I create a simple app to test but was getting a crash when the job kicked off until I added the Xamarin.Android.Support.v4 library.  Adding that library forced me then to add Support.Compat, Support.Core.UI, ...   Is there any reason why I need those other libraries in order to use the job dispatcher?

**Comment by topgenorth** [comment]
Good question - this might just be a "legacy thing" left over from an older version of the FJD that I was using. Looking into this.

**Comment by topgenorth** [comment]
So @mikevandre, yes the original Firebase JobDispatcher does require the Android Support v4 library. Forgot to declare that dependency in the NuGet. Fix is incoming so that adding the Xamarin.Firebase.JobDispatcher via NuGet will also ensure that Xamarin.Support.V4 is included as well.

Thanks for catching this!

**Comment by mikevandre** [comment]
@topgenorth:  For me, it was not enough to just add the Xamarin.Support.V4 library. It also required me to add the other libraries I listed above Support. compat, support.core.ui, etc.  Are all of these necessary?

**Comment by ericlee1974** [comment]
I have tried to build this sample project, but the nuget package for Xamarin.Firebase.JobDispatcher doesn't seem to be installed. When I install it (any of the pre-releases available) manually, I get the following error 
 
The "CreateLibraryResourceArchive" task failed unexpectedly.
Xamarin.Tools.Zip.ZipIOException: Error occured while reading ..\..\externals\firebase-dispatcher.aar
   at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictConsistencyChecks, IPlatformOptions options)
   at Xamarin.Android.Tasks.CreateLibraryResourceArchive.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Firebase.JobDispatcher			

Any idea what the problem is?

**Comment by topgenorth** [comment]
The NuGet is very out of date, and there is an [outstanding bug](https://bugzilla.xamarin.com/show_bug.cgi?id=59046) which prevents Xamarin.Android from compiling an updated binding.

Right now, there are two, or maybe three options I can suggest:
* use the Android Job Scheduler that is provided by Android in API level 21 and higher (this would be my recommendation)
* wait for 15.7 (and an updated binding of the library)
* bind the [Evernote android-job](https://github.com/evernote/android-job) library

**Comment by newky2k** [comment]
@mikevandre @ericlee1974 we pushed out an updated version to nuget at the end of may, can you try this out and see if it fixes your issues -> https://www.nuget.org/packages/Xamarin.Firebase.JobDispatcher/
