### ISSUE TITLE
Mono.Posix.NETStandard erronously (?) includes Framework reference to Mono.Posix

### ISSUE THREAD

**Issue by marek-safar** [xamarin/XamarinComponents#282]
_From @damageboy on December 26, 2017 17:44_

## Steps to Reproduce

1. git clone https://github.com/damageboy/mprefbug
2. export FrameworkPathOverride=/usr/lib/mono/4.6.2-api
3. Build fails

## Current Behavior
Currently when building for mono (net462) with dotnet on Linux/Mac, the Mono.Posix.NETStandard nuget adds an explicit reference to Mono.Posix.dll while also providing the same implementation inside the nuget.

As such, when building, msbuild will add references both to the nuget implementation and the Mono.Posix.dll provided as part of `/usr/lib/mono/4.6.2-api` for example, and fails thusly:

```
Microsoft (R) Build Engine version 15.4.8.50001 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

Class1.cs(8,9): error CS0433: The type 'Syscall' exists in both 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' [/tmp/mpref/mpref.csproj]

Build FAILED.

Class1.cs(8,9): error CS0433: The type 'Syscall' exists in both 'Mono.Posix.NETStandard, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' [/tmp/mpref/mpref.csproj]
    0 Warning(s)
    1 Error(s)
```

This doesn't no happen on Windows where Mono.Posix is not located in the reference assemblies folder(s).

## Expected Behavior

Build should work....

It is my suspicion that there is an error (?) on the Mono.Posix.NETStandard.nuspec as part of the nuget, which contains the following xml tags:
```xml
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="Mono.Posix" targetFramework=".NETFramework4.0" />
    </frameworkAssemblies>
```

I believe this is an error on the packaging side, which once removed should/would solve this issue, and the relevant Mono.Posix bits are already delivered INSIDE the nuget...

### On which platforms did you notice this

[x] macOS
[x] Linux
[ ] Windows

**Version Used**:

```
Mono JIT compiler version 5.4.1.6 (tarball Wed Nov  8 20:42:04 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen (concurrent by default)
```

_Copied from original issue: mono/mono#6341_

**Comment by marek-safar** [comment]
_From @damageboy on December 28, 2017 15:50_

Just so its clear, I've created my own hack version of Mono.Posix.NETStandard which does not use the framework assemblies and it work perfectly well on Linux where one would reasonably expect `Mono.Posix` as part of the mono installation...

**Comment by marek-safar** [comment]
@bholmes where do you want to track nuget bugs?

**Comment by marek-safar** [comment]
_From @bholmes on January 2, 2018 16:36_

@marek-safar https://github.com/xamarin/XamarinComponents

**Comment by marek-safar** [comment]
_From @damageboy on January 2, 2018 19:42_

Do you want me to reopen it there?

**Comment by damageboy** [comment]
Is there any progress/comment on this?

**Comment by bholmes** [comment]
I believe the latest version resolves the issue.

https://www.nuget.org/packages/Mono.Posix.NETStandard/1.0.0

**Comment by damageboy** [comment]
The nuspec still contains the problematic  `Mono.Posix` reference..

https://github.com/xamarin/XamarinComponents/blob/b3999764b5de09a8e0a735a91b153c59cf525979/XPlat/Mono.Posix/Mono.Posix.NETStandard.nuspec#L14

Do you want to me to open a new issue?

Again, to re-iterate, this cannot be built without a warning on Windows because there is no, and will be no Mono.Posix in the GAC / reference assemblies on the one hand

And causes the above mentioned complication error when compiling with `dotnet build` on linux on the other hand

Can someone comment on why they think this even makes sense, given the uniqueness of Mono.Posix in the mono ecosystem?

I currently stopped caring, since I have my own patched version of this, but I still think this is wrong.

**Comment by newky2k** [comment]
@damageboy  Thank you for your input but this project is really targeted towards .net core, rather than  the .net framework, and as such the requirement for that means that we cannot remove Mono.Posix as a frameworkassembly reference.

If you have an alternative solution that allows this to work for both, then please submit a pull request for us to consider.

Thanks

**Comment by damageboy** [comment]
You're right.
It pretty much feels like talking to a brick wall from where I am.
Bye.

**Comment by roji** [comment]
@newky2k

>  Thank you for your input but this project is really targeted towards .net core, rather than the .net framework, and as such the requirement for that means that we cannot remove Mono.Posix as a frameworkassembly reference.

Can you please explain the above? One of the main ideas of mono (so I thought) was to provide an implementation of .NET *Framework* on non-Windows platforms. If I want .NET Core, well, I can just use .NET Core - why would I need mono?

Also, can you please explain why Mono.Posix is required, either by .NET Framework *or* by .NET Core? Isn't that package about exposing POSIX APIs to users? Does the mono implementation of the BCL somehow depend on this package?

**Comment by ransagy** [comment]
I get the aforementioned warnings such as the OP talks about (after using the 1.0.0 release). I added this NuGet to a netstandard2.0 library i have, which is referenced in turn by both .NET Core (2.1 and 3.0) and .NET Framework (4.7.2) projects and now i get the warning for every single project that uses my library.

Is there really nothing that can be done to mitigate this warning spam?

**Comment by aleksandrov** [comment]
@newky2k any updates on this? As far as I see Mono.Posix duplicates functionality provided my Mono.Posix.NetStandard itself. Also @bholmes 's comment above (https://github.com/xamarin/XamarinComponents/issues/282#issuecomment-377930736) says it was fixed (but apparently not). Should we try once again?

Regards,
Dmytro

**Comment by jason-grimme** [comment]
@newky2k , I have experienced this issue on https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/1272#issuecomment-1967356018 and resolution is to cover up the Mono.Posix.Netstandard problem by manually adding reference to Mono.Posix prerelease nuget package.  

Why does this nuget package insist on having phantom dependency instead of just adding reference to Mono.Posix package?

**Comment by newky2k** [comment]
@jason-grimme Sorry that you are having issue with this still.  Unfortauntely, i'm no longer associated with Microsoft/Xamarin have left nearly 4 years ago now.  This wasn't a package I managed, I was just looking after the comments and PRs towards the end so i don't have any insight that might help here unfortunately.

@mattleibow  might be able to help, he was the last work on it, but i think this whole repo is unsupported now unfortunately.
