### ISSUE TITLE
Xamarin.Android.Crashlytics error: package io.fabric.sdk.android.services.events

### ISSUE THREAD

**Issue by Goncharuk-Nikita** [xamarin/XamarinComponents#460]
When I completed all the steps to add the Xamarin.Android.Crashlytics package when building, I get an exception:

```
error: package io.fabric.sdk.android.services.events does not exist
		io.fabric.sdk.android.services.events.EventsStorageListener
```

Microsoft Visual Studio Community 2017 
Version 15.8.4
VisualStudio.15.Release/15.8.4+28010.2026
Microsoft .NET Framework
Version 4.7.03062

Xamarin   4.11.0.756 (d15-8@b66ff7180)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   4.14.221 (a73ca07f7)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   1.1.116 (9619170)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   9.0.0.19 (HEAD/a8a3b0ec7)
Xamarin.Android Reference Assemblies and MSBuild support.

Xamarin.iOS and Xamarin.Mac SDK   11.14.0.13 (373c313)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

> VS bug [#732186](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732186)

**Comment by newky2k** [comment]
@Goncharuk-Nikita  could you try adding the Xamarin.Android.Crashlytics.Core package and see if that resolves the issue

Regards

**Comment by AlbertoBelver** [comment]
Hi @newky2k 
 I having the same problem than @Goncharuk-Nikita before and after add the Xamarin.Android.Crashlytics.Core package.

Microsoft Visual Studio Enterprise 2017
Version 15.7.5
Microsoft .NET Framework
Version 4.7.03062

Xamarin.Android.Crashlytics 2.9.4.1
Xamarin.Android.Crashlytics.Core 2.6.3

**Comment by ebelrose** [comment]
As it's seems related to my issue #460 I'm posting here too.

Visual Studio Community 2017 for Mac
Version 7.6.7 (build 49)
Installation UUID: c2bfe105-bf10-425c-8fd8-70583757c2f8
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

.NET Core
Runtime : /usr/local/share/dotnet/dotnet
Version du runtime : 2.1.2
SDK : /usr/local/share/dotnet/sdk/2.1.302/Sdks
Version du SDK : 2.1.302
SDK MSBuild : /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Android
Version : 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/ebelrose/Library/Android/sdk
	Versions Android prises en charge :
		5.1(Niveau d’API 22)
		7.0(Niveau d’API 24)
		8.1(Niveau d’API 27)

Version de SDK Tools : 26.1.1
Version des outils de plateforme du SDK : 28.0.1
Version des outils de génération du SDK : 28.0.2

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Operating System
Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by ninaada** [comment]
Even I'm facing the same issue.

**Comment by pooran** [comment]
same here. any resolution?

**Comment by newky2k** [comment]
I've assigned this to @Redth to investigate

**Comment by Redth** [comment]
Can you post diagnostic build logs please?

Also check that `~/Library/Caches/XamarinBuildDownload/fabric-1.4.3/fabric.aar` exists. My guess is something is happening to cause this file not to download properly during the build.

**Comment by rickjansen-dev** [comment]
I had the same error. I noticed that the xamarin build download cache did not have any fabric-* directory (using windows myself, so it's in `%USERPROFILE%\AppData\Local\XamarinBuildDownloadCache\`).

Installed `Xamarin.Android.Fabric` NuGet package and now the folder is there (including fabric.aar) and project builds.

After that, i got some error at runtime due to missing java class definitions. To get the app working, I also had to manually install `Xamarin.Android.Crashlytics.Answers` and `Xamarin.Android.Crashlytics.Core` and `Xamarin.Android.Crashlytics.Beta` (basically all dependencies if i'm correct)
Installing packages created folders for each package in that xamarin build download cache directory.

**Comment by newky2k** [comment]
@vuurbeving Thanks for the update

**Comment by jakovvidekovic** [comment]
@newky2k  Is there going to be a solution for this? I would really like to add Crashlytics to my Xamarin app

**Comment by newky2k** [comment]
@JackTrbosjek @Redth is still looking into it and will have a resolution for you soon.

Regards

**Comment by Redth** [comment]
I believe this is fixed.  The latest version includes the previously mentioned packages as explicit dependency references.

**Comment by AlbertoBelver** [comment]
Thanks I´ll try it.

**Comment by masterwok** [comment]
What version was this resolved in? I'm seeing this issue in version 2.9.4.1.

**Comment by jaylindelycke** [comment]
> What version was this resolved in? I'm seeing this issue in version 2.9.4.1.

Me too in same version (latest). 
I had to do as @vuurbeving did; manually add Xamarin.Android.Fabric, which gave runtime error, then also add Xamarin.Crashlytics.Core, Answers and Beta.

**Comment by tiagocrizanto** [comment]
@jaylindelycke try add Xamarin.googleplayservices.Gcm (Google Cloud Messaging) package

**Comment by Lewy-H** [comment]
I had to add every package shown in the license acceptance dialog manually. The full list is as follows:

* Xamarin.Android.Crashlytics
* Xamarin.Android.Crashlytics.Answers
* Xamarin.Android.Fabric
* Xamarin.Android.Crashlytics.Beta
* Xamarin.Firebase.Analytics
* Xamarin.Firebase.Analytics.Impl
* Xamarin.Firebase.Common
* Xamarin.Firebase.Core
* Xamarin.Firebase.Iid
* Xamarin.GooglePlayServices.Basement
* Xamarin.GooglePlayServices.Tasks

I then cleaned the solution, closed the solution, reopened it and rebuilt it and it worked. Not sure if the order of those last steps had any effect or not.

**Comment by b12kab** [comment]
This error just occurred on a project that I am working on - after I cleaned the nuget locals cache.

As a matter of fact, I added all of the items that @Lewy-H noted - trying to figure out a Google Analytics non-communcation problem; cleared the cache, deleted the bin and obj folders in all solutions and now I start getting this error.

I removed all of the above and re-added Xamarin.Android.Crashlytics v2.9.4.1. It then asked me to approve the license for the above 11 list items in @Lewy-H 's list. I did so. A clean and Android build, and I still get the error though. :(

In case it has any bearing on the matter, I'm using Xamarin.Build.Download 0.4.12-preview3 - because of other [Xamarin / Google build problems](https://github.com/xamarin/XamarinComponents/issues/444)

**Comment by b12kab** [comment]
I removed them all, cleared cache and re-added them again. This time it worked; no real answer to why it didn't work the first few times and worked now.

I should have noted that at the beginning of today's session, I upgraded to: Visual Studio Enterprise 2017 for Mac Version 7.8.2 (build 1).

**Comment by orestesgaolin** [comment]
@Redth please reopen this issue or open new one as the problem still occurs if we use only Xamarin.Android.Crashlytics

**Comment by juanagu** [comment]
@Lewy-H Thanks! works for me!

**Comment by acaliaro** [comment]
Today, installing only Xamarin.Android.Crashlytics, I have the same problem

**Comment by acaliaro** [comment]
@Redth can you take a look, thanks

[fabricerror.zip](https://github.com/xamarin/XamarinComponents/files/3279833/fabricerror.zip)

**Comment by acaliaro** [comment]
@Redth can you take a look
thanks
[fabricerror.zip](https://github.com/xamarin/XamarinComponents/files/3279839/fabricerror.zip)

**Comment by kyluke** [comment]
Installing `Xamarin.Build.Download` helped me.

**Comment by Alexander-Alekseev** [comment]
I faced with the same problem today. I'm not sure, but probably the reason is that my solution is Xamarin.Forms solution, not a Xamarin.Android (I tried to add Xamarin.Android.Crashlytics to the Android-specific project though). And/or probably because of `Xamarin.Firebase.Messaging` & `Xamarin.GooglePlayServices.Base` references that I already had in my project.

Btw, my (workaround) solution is similar to @Lewy-H + @kyluke solutions. I split added references to 4 categories (the order does matter):
1) "Prerequisites":
```
Xamarin.GooglePlayServices.Basement
Xamarin.Firebase.Common
Xamarin.GooglePlayServices.Tasks
Xamarin.Firebase.Iid
```
2) `Xamarin.Android.Crashlytics` itself.
3) Xamarin.Android.Crashlytics' dependencies (they were not downloaded automatically, so I added them manually):
```
Xamarin.Android.Crashlytics.Answers
Xamarin.Android.Fabric
Xamarin.Android.Crashlytics.Beta
Xamarin.Firebase.Core
Xamarin.Build.Download
```
4) Others:
`Xamarin.Android.Crashlytics.Core`
