### ISSUE TITLE
.locked file extension

### ISSUE THREAD

**Issue by gmenezesg** [xamarin/XamarinComponents#479]
Please change the .locked file extension for any other extension or allow us to choose the extension name, since the .locked is a well known extension used by ransomware. At a corporate environment, some antivirus solutions block this extension.

> VS bug [#732189](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732189)

**Comment by newky2k** [comment]
@gmenezesg Could you please be a bit more specific?  What are you referring to exactly?

Regards

**Comment by Redth** [comment]
Guessing this is Xamarin.Build.Download.  The `.locked` is what we use.  Sad that antivirus software is just checking filenames instead of heuristics :(.  But we can consider changing this in future versions.

**Comment by Redth** [comment]
After looking into this, it's a bit more complicated than just switching the filename.  The problem is the `.locked` file is used to ensure there is no contention across projects or even separate instances of visual studio while working on a file that might be used by these instances (we try and obtain an exclusive write lock to this file).

If we change the filename on a newer version of Xamarin.Build.Download we risk other projects or instances of the IDE still using older versions of Xamarin.Build.Download, and the old filename, and so we risk contention.

Unfortunately this doesn't look like something we should change.  The advice for now is to set an exception for .locked files in the particular path they are found `%localappdata%\XamarinBuildDownloadCache`.
