### ISSUE TITLE
Xamarin.Android.PhotoView SetScale only works if "animate" is set to true

### ISSUE THREAD

**Issue by Jelb** [xamarin/XamarinComponents#481]
Calling `ImageViews.Photo.PhotoView.SetScale(float scale, bool animate)` does not update the view unless the animate argument is set to true.

**Comment by newky2k** [comment]
@Jelb  do you know if this an issue with the underlying library, rather than the binding?  this is the line in the source library, looks like it treats it differently.  

https://github.com/chrisbanes/PhotoView/blob/master/photoview/src/main/java/com/github/chrisbanes/photoview/PhotoViewAttacher.java#L451

**Comment by newky2k** [comment]
Closing no further information was provided
