### ISSUE TITLE
SceneForm's ShapeFactory methods are missing

### ISSUE THREAD

**Issue by dotMorten** [xamarin/XamarinComponents#584]
The ShapeFactory class is there, but the 3 important static methods are not on it.
Here's all I see in Visual Studio:
![image](https://user-images.githubusercontent.com/1378165/58533248-d3372a80-819c-11e9-86d8-7d6958eac3eb.png)

However the doc shows 3 static methods:
https://developers.google.com/ar/reference/java/sceneform/reference/com/google/ar/sceneform/rendering/ShapeFactory

**Comment by CodeGenie1** [comment]
I think the bindings for the 3 Make methods are failing because they need a reference to Vector3 that is part of the Sceneform.Base library.  The Rendering library does not currently contain a reference to Base.

I managed to fix this by copying over just the rendering project and adding the reference via nuget pacakge.

Also need to add 
`<remove-node path="/api/package[@name='com.google.ar.sceneform.rendering']/class[@name='Renderable.Builder']/method[@name='getRenderableRegistry' and count(parameter)=0]" />`

to the end of the Transforms\Metadata.xml  file in Rendering library project to strip out the abstract class definition.

**Comment by Redth** [comment]
Would love some community help here if anyone's interested in a PR :)

**Comment by newky2k** [comment]
@CodeGenie1  I have added these changes as part of the 1.9.0 update
