### ISSUE TITLE
Xamarin.tvOS with SDWebImage cannot generate bitcode

### ISSUE THREAD

**Issue by segfaults-behind-you** [xamarin/XamarinComponents#593]
Hello,

When I use SDWebImage in Xamarin.tvOS application it looks like it cannot generate bitcode.

Nuget package can be added to the project but when namespace is introduced anywhere in the code, the final file seems to not contain bitcode.

*.ipa file is generated but when I try to upload it through Application Loader, I get such response from Apple: 
"ITMS-90496: Invalid Executable - The executable '{APP_NAME}.app/{APP_NAME}' does not contain bitcode."
Where {APP_NAME} it the name of my application.

When I remove SDWebImage everything works as intended and bitcode is present.

Is it possible to get bitcode when using SDWebImage?
Maybe I am missing something.

**Comment by newky2k** [comment]
@szymonkalista I think this is because the underlying native library  in the current version doesn't support bitcode either or possible TvOS.

We are in the process of updating the binding to the latest version of SDWebImage, #589, and hopefully  this should resolve the issue for you.

**Comment by newky2k** [comment]
@szymonkalista  The new 5.x version of SDWebImage is substantially different, so I've gone back and checked the .a files included in the current tvos dll and both of them include bitcode.

It turns out that SDWebImage include tvOS support and bitcode in October 2015

How are you generating the IPA file?

**Comment by segfaults-behind-you** [comment]
@newky2k Hello, sorry for the late reply. 
We are using the build task for iOS that is available in Azure DevOps, because there is no task for tvOS present and it did job for us, until we have included SDWebImage. 
This may be the problem. 
Maybe we can use some MsBuild parameter that prevents this bitcode skipping? 
Or maybe you could point me to some source that describes using MSBuild directly?

The interesting part is that it was working fine before SDWebImage was added.

If you need any more info, let me know I'll try my best to provide it.

**Comment by segfaults-behind-you** [comment]
@newky2k Hey! I saw the issue #601 it looks like the same problem my team is currently having. I had some time today to look into this. I do not know whether I am looking in the right direction but here's what I've gathered, maybe this will help a bit with resolving this issue.

I see that in Native References for SDWebImage.tvOS you are using libwebp. I've checked this library with otool, to check whether it supports bitcode, because from what I've gather every static library, dynamic library (third-party also) should be built with bitcode support.

To check whether a library supports the bitcode this command can be used:
otool -l {PATH_TO_LIBRARY}/{LIB_NAME}.a | grep __LLVM

this should return section as described here:
https://docs.microsoft.com/en-us/xamarin/ios/tvos/troubleshooting
Section: Verifying that your tvOS App Contains Bitcode

By the looks of it, this lib does not support bitcode, maybe this is why the bitcode cannot be generated while using SDWebImage in Xamarin.tvOS apps. 

Also I saw that in #601 final app size is mentioned. 
When bitcode is properly generated the final app is bigger in size due to the fact that it contains bitcode. When app does not contain bitcode the size is smaller.

Our app - when we do not use SDWebImage, and bitcode is present - is around 180MB.
When we use SDWebImage - and the bitcode is not present, we get around 80MB.

This is expected behaviour.

Please, let me know if this info is of any use for you and whether this issue can be resolved somehow.

**Comment by newky2k** [comment]
@szymonkalista  thank you for the information.  @SotoiGhost is helping me look into this.

**Comment by SotoiGhost** [comment]
@rishabh14augshukla @szymonkalista can you try this NuGet and let me know your results? Thanks in advance!

https://www.dropbox.com/s/0qwlkakqla1cy6l/Xamarin.SDWebImage.4.4.6.1.nupkg?dl=0

**Comment by segfaults-behind-you** [comment]
@SotoiGhost I did a local release build of our application and I've checked for bitcode - with this package it is generated properly. App size seems about right and I've also checked for __LLVM tag with otool, and it exists. Which is awesome!

I'll try to upload it to AppStore later and I'll let you know whether everything is correct but by the looks of it, everything should be fine. Thanks!

Could you please tell me what had to be done in order to make it work?
Why the bitcode could not be generated before?

**Comment by rishabh14augshukla** [comment]
@SotoiGhost  I also used the new SDWebImage which is provided by you and App size is perfect and next I am going to upload this build on App Store then We will see the actual result.
 
@SotoiGhost  You are awesome :)

**Comment by SotoiGhost** [comment]
@szymonkalista @rishabh14augshukla Glad to know that it's working!  And sorry for the inconveniences that this issue caused.

The problem was when building the native bits. We had enabled the `ENABLE_BITCODE` to `YES` but we needed to change another setting named `BITCODE_GENERATION_MODE` so the bitcode could be generated correctly.

`BITCODE_GENERATION_MODE` is set to `marker` by default which means that only generates an empty bitcode when building on **Debug**/**Release** and will only generate the full bitcode until you build and archive your library. Setting it to `bitcode` will generate a full bitcode when building on **Debug**/**Release**. So what we learned is that even if we could find `__LLVM` (bitcode) inside of a library it doesn't mean it really has bitcode. You need to check the size of the bitcode.

You can check the size by running the following command:

```bash
otool -arch {ARCH} -l {PATH_TO_LIBRARY}/{LIB_NAME}.a | grep -C 2 __LLVM
```

**_Command output of library with `BITCODE_GENERATION_MODE=marker`_**
<img width="300" src="https://user-images.githubusercontent.com/5924210/64814004-3db38100-d568-11e9-8ad8-6fd490360b51.png" />

**_Command output of library with `BITCODE_GENERATION_MODE=bitcode`_**
<img width="300" src="https://user-images.githubusercontent.com/5924210/64814021-4441f880-d568-11e9-8071-fad1e1f41ee3.png" />

I'll wait for the upload result. 🤞🏼Hope it will work.

**Comment by newky2k** [comment]
We have pushed out a new version of 4.x(4.4.7) which includes the fix for TV OS bitcode and also xcode 11

**Comment by rishabh14augshukla** [comment]
@SotoiGhost I have good news for you. After using 4.4.7 SDWebImage library in Xamarin tvOS. App Store accepted tvOS build.

Good Job and Thanks @SotoiGhost

**Comment by newky2k** [comment]
@rishabh14augshukla  Thats great news!!!

**Comment by rishabh14augshukla** [comment]
Yes, @newky2k. This is good news for us.
