### ISSUE TITLE
Update Arcore and Sceneform to version 1.11

### ISSUE THREAD

**Issue by a-iafrate** [xamarin/XamarinComponents#608]
Google have released ARCore and Sceneform 1.10 and the component need to be updated, please update quickly!

**Comment by craigktreasure** [comment]
@Redth, we'd like to take an update as well. Thanks!

**Comment by Redth** [comment]
On our todo list unless someone beats us to it!

**Comment by spixy** [comment]
There is ARCore v1.11 now :)

**Comment by a-iafrate** [comment]
title updated 👍

**Comment by craigktreasure** [comment]
@Redth Hypothetically, if someone were to contribute this, are there a list of steps with the testing due diligence?

**Comment by Redth** [comment]
This is a smaller library but basically we're looking for the basic sample working as a 'test'.  We unfortunately don't have the resources to do much testing beyond this, though often for smaller API's it's not hard to open the .jar files in JD-GUI or something similar and just eyeball that the types in the .jar exist also in the binding .dll that was generated.  The nice thing is even if we miss a type or member in our binding, there's no real harm other than you can't use it until we surface it and release an update with the 'fix'.

**Comment by craigktreasure** [comment]
Cool. I got some time today to take a look at updating these.

I've got all of the changes to take us to 1.10.0 and then 1.11.0 in my fork for both ARCore and SceneForm. I've also validated both the ARCore and SceneForm samples for both versions. It's just going to take some time to feed PRs through to the Xamarin team since we have to take them one by one.

I've started with updating to ARCore 1.10.0 in #629. Once that is in and we get an updated ARCore 1.10.0 NuGet package, we can then do ARCore 1.11.0 and SceneForm 1.10.0 in parallel followed by SceneForm 1.11.0. It's just about how much time the Xamarin team has to look at PRs.

**Comment by a-iafrate** [comment]
Wow this is good news, can you also take a look at the missing namespace in sceneform? [#609](https://github.com/xamarin/XamarinComponents/issues/609) :P
Thanks!!

**Comment by craigktreasure** [comment]
@a-iafrate I could maybe take a quick look, but it's possible that it may require more practiced hands. I'm still very much a bindings newbie 😉.

**Comment by craigktreasure** [comment]
Maybe by taking this issue off their plate, the Xamarin team will have more time to focus on those other more difficult issues!
