### ISSUE TITLE
Xamarin.build.download does not allow prerelease IDs

### ISSUE THREAD

**Issue by nrbrook** [xamarin/XamarinComponents#738]
The regex here: https://github.com/xamarin/XamarinComponents/blob/4fc12c1d34627de903041cc1afcbaba7611065b5/Util/Xamarin.Build.Download/source/Xamarin.Build.Download/DownloadUtils.cs#L201 does not allow prerelease IDs such as `Package-1.0.0-b.1`

**Comment by Redth** [comment]
@nrbrook can you give me an example of what you're trying to use this for?  And iOS or Android? I think the best bet for now would be to change the id string you use to be compliant with the rules, yet still unique to that version (eg: `Package100b1-1` or something).   I'd love to know more about your use case though as we don't generally see any usage of Xamarin.Build.Download external to our own use cases.

**Comment by nrbrook** [comment]
My use case is we have a precompiled framework for iOS and we don’t want to distribute it publicly. So we have the thin xamarin binding on nuget which downloads the zip containing the framework. See [AirTurnUI](https://www.nuget.org/packages/AirTurn.iOS.AirTurnUI/3.7.0-b.4). I now use a transform to make it work:
```
<XamarinBuildDownload Include="AirTurnInterface-$(_AirTurnInterfaceVersion.Replace('-','')">
```

**Comment by appsourcers** [comment]
@nrbrook I believe he's saying you should roll your own.

**Comment by mattleibow** [comment]
@appsourcers I think that @Redth is actually meaning that technically Xamarin.Build.Download should not be used. We use it because we do not have legal permission to distribute jar/aar files for some projects. For some projects, the license is MIT or Apache so we don't use Xamarin.Build.Download there. In other cases, there is a custom license that explicitly states that WE cannot distribute it. Thus, we created Xamarin.Build.Download to download the files on your machine.

If you are creating your own libraries, then you should download the jar/aar files let the defaults embed the the files into the dlls. The ONLY reason why you might use Xamarin.Build.Download is if you are creating PUBLIC NuGets and you don't have permission to distribute the aars. If you are creating internal NuGets, I believe that even then you can store the aars inside the package. If you can, you should include the aars in the NuGet package as this is a much better experience for the user as the IDE might block while it goes and downloads the aars.

**Comment by jpobst** [comment]
This should be fixed by https://github.com/xamarin/XamarinComponents/pull/1384.
