### ISSUE TITLE
IOS ITMS-90809: Deprecated API Usage UIWebView

### ISSUE THREAD

**Issue by Manne990** [xamarin/XamarinComponents#745]
The native component fixed this in September.
https://github.com/material-components/material-components-ios/commits/9bd8770ae49884f2fe7889a2441ea03d46ef9e87/components/BottomSheet/src/MDCBottomSheetPresentationController.m

When will there be a new Xamarin component released that includes this fix?

**Comment by appsourcers** [comment]
@Manne990 Good news is that it's cooking in https://github.com/xamarin/XamarinComponents/pull/664. 
But the bad news is that maintainers have their efforts concentrated elsewhere. I apologize if that's not the case @mattleibow and @newky2k?

It's just that today is almost 3 months from what looked like a simple ApiDefinition update.
Inertness we witness here, specifically to ITMS-90809 is really worrying to all involved, I'm sure. 
It's pressing all of us to do extra work that could have been avoided had we looked away from official support. It forces us to maintain our own repos, pipelines, nuget servers and whatnot. 
And all that make this official support pointless.

ITMS-90809 is of real concern because there's no guarantee that we will have this MaterialComponents update in time before Apple decides to stop accepting builds!
And so the question stands, why hasn't this seemingly simple PR https://github.com/xamarin/XamarinComponents/pull/664 merged in yet? 
Where is the transparency behind this prolonged decision making?

cc: @Redth @jamesmontemagno

**Comment by Redth** [comment]
@appsourcers unfortunately PR #664 is anything but simple, and in its current state, very much a work in progress.  The API changes between MaterialComponents v72 and v92 (or v94 for that matter) are significant, and to make matters worse, diffing the header files between those two versions generates a _lot_ of noise, making it rather inefficient to manually grep the changes and apply them to the existing ApiDefinition.  In a lot of ways it would be easier to start with a fresh Objective-Sharpie generated ApiDefinition, however there is significant effort in that approach too given all of the name changes and other tweaks that were applied to the previous ApiDefinition which we wouldn't want to lose and cause major API breaks (especially since Xamarin.Forms Material Visual depends on this binding).  

We have someone working full time right now on building some tools to help make the ApiDefinition change process more manageable for this update and future updates, and their only goal right now is to find a way to finish this update, and ensure future updates can be done much more quickly.  So, we are heavily investing in supporting this binding, however it's a lot of work.

Hopefully that helps provide some transparency to the matter.

**Comment by appsourcers** [comment]
@Redth It does. Very much appreciated and good luck!

**Comment by newky2k** [comment]
@Manne990  @appsourcers  v92 RC1 is live on nuget as a pre-release -> https://www.nuget.org/packages/Xamarin.iOS.MaterialComponents/92.0.0-rc1
