### ISSUE TITLE
Crashlytics not working

### ISSUE THREAD

**Issue by guillermo-gerard** [xamarin/XamarinComponents#755]
That's it, I've tried to integrate Crashlytics in my project and it didn't work (expected, it happens a lot working with xamarin)
Then I've tried the sample and it didn't work (don't even compiles)
I then tried to create a project from scratch with only the crashlytics functionality (similar to the sample, and I've got this:
error: package com.crashlytics.android.core does not exist
		com.crashlytics.android.core.CrashlyticsListener
error: package io.fabric.sdk.android.services.events does not exist
		io.fabric.sdk.android.services.events.EventsStorageListener

Did somebody get this working at least once, or it is a waste of my time just to try it out?

**Comment by mattleibow** [comment]
Hi @guillermo-gerard thanks for reporting this. I understand your frustration as I just experienced this very issue this week and it took a little while to figure it out.

I believe it has to do with the way nuget handles dependencies when using `<PackageReference>`. I opened this issue in this repo to track it (I am working on it right now): https://github.com/xamarin/XamarinComponents/issues/754

What is happening is that you are referencing Crashlytics, and that has some dependencies. The problem is that nuget has decided that the targets files (that brings in the jar files) are not needed - which is wrong.

The workaround for this is just to install all the packages in the dependency chain into your app:
 - Xamarin.Android.Crashlytics
 - Xamarin.Android.Crashlytics.Answers
 - Xamarin.Android.Crashlytics.Beta
 - Xamarin.Android.Crashlytics.Core
 - Xamarin.Android.Fabric

Here is a handy copy-paste for you (installed Xamarin.Build.Download as well to make sure everything is up-to-date):

```xml
<PackageReference Include="Xamarin.Android.Crashlytics" Version="2.9.4.1" />
<PackageReference Include="Xamarin.Android.Crashlytics.Answers" Version="1.4.2" />
<PackageReference Include="Xamarin.Android.Crashlytics.Beta" Version="1.2.9" />
<PackageReference Include="Xamarin.Android.Crashlytics.Core" Version="2.6.3" />
<PackageReference Include="Xamarin.Android.Fabric" Version="1.4.3" />
<PackageReference Include="Xamarin.Build.Download" Version="0.7.0" />
```

I have a fix in progress that should make all this work unnecessary (as it should): #757

**Comment by mattleibow** [comment]
@guillermo-gerard, Just pushed out package updates to fix this issue. You should _just_ need to install the single `Xamarin.Android.Crashlytics` v2.9.4.1 package and it should correctly pull in the dependencies and download the native files.

```xml
<PackageReference Include="Xamarin.Android.Crashlytics" Version="2.9.4.2" />
```

**Comment by guillermo-gerard** [comment]
Thank you @mattleibow , this certainly fixes the build problem I had, and it is working in my minimal test app.
However, In the actual project, this is still not working. I mean: I can do a build and deploy to test device but then, when I throw the exception, nothing is logged. I'm initializing fabric (The line Fabric.Fabric.With(...))  in the Application's  OnCreate; so, could be this the cause of the exceptions not available in the firebase console?
I've added the exact nuget packages you mention, I've checked that the  "google-services.json" file is there and with the correct build action, the string  "com.crashlytics.android.build_id" is in place, and the project created in the firebase console, of course. Any clue about what else I can check?

**Comment by mattleibow** [comment]
I would suggest opening a new issue with Crashlytics not working and tagging @Redth as he knows how that library actually works. I just know about the packaging. He is in east Canada, so he should be coming online in a bit. Just link to the new issue and I will make sure he knows about it as soon as I see him online.

**Comment by mattleibow** [comment]
Also, is there maybe some delay in the exceptions getting logged? I know other crash reporting libraries need a little time. And, most require that the app launch successfully again so that it can actually send it.

**Comment by guillermo-gerard** [comment]
No, there is almost no delay when it works.
I think I found what is causing the issue and I will add the relevant information in the new issue, thank you Matthew!
