### ISSUE TITLE
ManifestMerger Exits with Code 1 on build (preview 03)

### ISSUE THREAD

**Issue by ncosentino** [xamarin/XamarinComponents#893]
This seemed very related to [ManifestMerger error on build (preview 03) #734](https://github.com/xamarin/XamarinComponents/issues/734) but that was marked as resolved and I didn't want to conflate anything.

I'm in the process of trying to add AdMob support to my application, and just referencing the nuget package (with no other code changes) is enough to cause visual studio to fail compilation now.

The output I'm seeing is:

```
2>C:\Users\MyLocalUser\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\Xamarin.Android.ManifestMerger.targets(28,5): error MSB3073: The command ""C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\java.exe" -cp "C:\Users\MyLocalUser\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\common.jar;C:\Users\MyLocalUser\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\guava.jar;C:\Users\MyLocalUser\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\kotlin-stdlib-jdk8.jar;C:\Users\MyLocalUser\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\kotlin-stdlib.jar;C:\Users\MyLocalUser\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\kxml2.jar;C:\Users\MyLocalUser\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\manifest-merger.jar;C:\Users\MyLocalUser\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\sdk-common.jar;C:\Users\MyLocalUser\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\sdklib.jar" "com.android.manifmerger.Merger" --main "obj\Debug\90\android\AndroidManifest.xml" --libs "obj\Debug\90\lp\10\jl\AndroidManifest.xml;obj\Debug\90\lp\16\jl\AndroidManifest.xml;obj\Debug\90\lp\18\jl\AndroidManifest.xml;obj\Debug\90\lp\20\jl\AndroidManifest.xml;obj\Debug\90\lp\21\jl\AndroidManifest.xml;obj\Debug\90\lp\22\jl\AndroidManifest.xml;obj\Debug\90\lp\23\jl\AndroidManifest.xml;obj\Debug\90\lp\24\jl\AndroidManifest.xml;obj\Debug\90\lp\25\jl\AndroidManifest.xml;obj\Debug\90\lp\26\jl\AndroidManifest.xml;obj\Debug\90\lp\27\jl\AndroidManifest.xml;obj\Debug\90\lp\28\jl\AndroidManifest.xml;obj\Debug\90\lp\29\jl\AndroidManifest.xml;obj\Debug\90\lp\30\jl\AndroidManifest.xml;obj\Debug\90\lp\31\jl\AndroidManifest.xml;obj\Debug\90\lp\32\jl\AndroidManifest.xml;obj\Debug\90\lp\33\jl\AndroidManifest.xml;obj\Debug\90\lp\34\jl\AndroidManifest.xml;obj\Debug\90\lp\35\jl\AndroidManifest.xml;obj\Debug\90\lp\36\jl\AndroidManifest.xml;obj\Debug\90\lp\37\jl\AndroidManifest.xml;obj\Debug\90\lp\38\jl\AndroidManifest.xml;obj\Debug\90\lp\39\jl\AndroidManifest.xml;obj\Debug\90\lp\40\jl\AndroidManifest.xml;obj\Debug\90\lp\41\jl\AndroidManifest.xml;obj\Debug\90\lp\42\jl\AndroidManifest.xml;obj\Debug\90\lp\43\jl\AndroidManifest.xml;obj\Debug\90\lp\44\jl\AndroidManifest.xml;obj\Debug\90\lp\45\jl\AndroidManifest.xml;obj\Debug\90\lp\48\jl\AndroidManifest.xml;obj\Debug\90\lp\49\jl\AndroidManifest.xml;obj\Debug\90\lp\5\jl\AndroidManifest.xml;obj\Debug\90\lp\50\jl\AndroidManifest.xml;obj\Debug\90\lp\51\jl\AndroidManifest.xml;obj\Debug\90\lp\52\jl\AndroidManifest.xml;obj\Debug\90\lp\53\jl\AndroidManifest.xml;obj\Debug\90\lp\54\jl\AndroidManifest.xml;obj\Debug\90\lp\55\jl\AndroidManifest.xml;obj\Debug\90\lp\56\jl\AndroidManifest.xml;obj\Debug\90\lp\61\jl\AndroidManifest.xml;obj\Debug\90\lp\62\jl\AndroidManifest.xml;obj\Debug\90\lp\63\jl\AndroidManifest.xml;obj\Debug\90\lp\64\jl\AndroidManifest.xml;obj\Debug\90\lp\65\jl\AndroidManifest.xml;obj\Debug\90\lp\66\jl\AndroidManifest.xml;obj\Debug\90\lp\67\jl\AndroidManifest.xml;obj\Debug\90\lp\68\jl\AndroidManifest.xml;obj\Debug\90\lp\69\jl\AndroidManifest.xml;obj\Debug\90\lp\7\jl\AndroidManifest.xml;obj\Debug\90\lp\70\jl\AndroidManifest.xml;obj\Debug\90\lp\71\jl\AndroidManifest.xml;obj\Debug\90\lp\72\jl\AndroidManifest.xml;obj\Debug\90\lp\73\jl\AndroidManifest.xml;obj\Debug\90\lp\74\jl\AndroidManifest.xml;obj\Debug\90\lp\75\jl\AndroidManifest.xml;obj\Debug\90\lp\76\jl\AndroidManifest.xml;obj\Debug\90\lp\77\jl\AndroidManifest.xml;obj\Debug\90\lp\8\jl\AndroidManifest.xml;obj\Debug\90\lp\9\jl\AndroidManifest.xml" --out "obj\Debug\90\android\AndroidManifest.xml"" exited with code 1.
```

Here's a screenshot that might make it a bit easier to read:
![image](https://user-images.githubusercontent.com/5169280/84073477-dd3e5c80-a99e-11ea-8636-7c1231ca617e.png)

And from following the other thread, I figured I'd try playing around with this command directly on the command line. It was saying:
```
obj\Debug\90\android\AndroidManifest.xml does not exist
```

When in fact the file did exist. I double checked from the directory I was running in as well, and relatively it should have all lined up. Even the casing was correct. I figured I'd try replacing the two instances of that relative path with the full path (instead of relative) annnnnd it worked (i.e. didn't print an error).

So at this point:
- I have no idea if the generated manifest is even correct (I did confirm the timestamp updated so it was at least touched)
- I have no idea how I could force visual studio to use the full path to test if it would actually correct the issue.

My list of package is as follows:
```
<ItemGroup>
    <PackageReference Include="Xamarin.Android.Crashlytics">
      <Version>2.9.4.4</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Android.ManifestMerger">
      <Version>1.0.0-preview03</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.Analytics">
      <Version>71.1630.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.Auth">
      <Version>71.1605.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.Common">
      <Version>71.1610.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.Iid">
      <Version>71.1710.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Firebase.Messaging">
      <Version>71.1740.0</Version>
    </PackageReference>
    <PackageReference Include="Xamarin.Forms" Version="4.5.0.530" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.2" />
    <PackageReference Include="Xamarin.GooglePlayServices.Ads.Lite">
      <Version>71.1720.2</Version>
    </PackageReference>
  </ItemGroup>
```
And for total transparency, everything functions properly (no code changes) EXCEPT for when I add the Xamarin.GooglePlayServices.Ads.Lite. I have tried all of the older nuget versions of this package and it still fails for the same reason.

Please let me know if there's other details I can provide that would help!

**Comment by ncosentino** [comment]
Just wanted to offer more context... from my working state, I decided I wanted to go update some nuget packages I had. But just revving these nuget packages breaks things in the same way:

Shared Project:
![image](https://user-images.githubusercontent.com/5169280/84611114-d6c25000-ae8a-11ea-8097-9b7ce67e724e.png)

Android Project:
![image](https://user-images.githubusercontent.com/5169280/84611128-e6419900-ae8a-11ea-872f-53310cad1ea2.png)

Not sure if that helps at all, but I'm assuming revving these versions causes one of the dependencies to need to add more onto that command line for the manifest merger and it explodes.

**Comment by ivmazurenko** [comment]
Same issue

**Comment by stepheaw** [comment]
I updated to the latest version of all the android firebase packages and updated to android X in my consuming project. I then removed the manifest merger package. It seems like I don't need this manifest merger package anymore since the main reason why I added it was because Firebase.Instance was null in my Firebase Notifications Project. It's not null anymore so I think I can remove the manifest merger now. I'm not sure about @ncosentino problem because I've never used  Xamarin.GooglePlayServices.Ads.Lite before

**Comment by RedChops** [comment]
I just hit this as well, though for me the error I'm getting is `obj\Debug\android\AndroidManifest.xml does not exist`. When I look through the obj\Debug folder though, I see that AndroidManifest.xml is actually in `obj\Debug\AndroidManifest.xml` instead of \android. Copying it to \android works as a workaround, but it's annoying to have to remember to do that if I clean the project

**Comment by brendanzagaeski** [comment]
I haven't contributed to the manifest merger NuGet package myself, but I noticed this discussion by chance, and it caught my eye because the latest recommended way to use Google's manifest merger is now [part of Xamarin.Android itself](https://docs.microsoft.com/xamarin/android/release-notes/10/10.2#improved-android-manifest-merging).

I tried a couple quick tests around this locally:

- I installed Xamarin.GooglePlayServices.Ads.Lite version 71.1720.2 and Xamarin.Android.ManifestMerger version 1.0.0-preview03 into a new template app and built the project. I saw the reported error:

  ```
  obj\Debug\90\android\AndroidManifest.xml does not exist
  ```

- I then uninstalled Xamarin.Android.ManifestMerger version 1.0.0-preview03 and enabled the new manifest merger support that's part of Xamarin.Android by adding the following lines to the Android app project _.csproj_ file ([using the text editor in Visual Studio](https://docs.microsoft.com/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2019#edit-project-files-in-visual-studio)):

  ```
  <PropertyGroup>
    <AndroidManifestMerger>manifestmerger.jar</AndroidManifestMerger>
  </PropertyGroup>
  ```

  After that, the project built successfully, and importantly, it successfully ran the `ManifestMerger` task.

Summary: I believe the Xamarin.Android.ManifestMerger NuGet package can now be considered obsolete. Project authors would be recommended to remove that NuGet package and instead set the `<AndroidManifestMerger>manifestmerger.jar</AndroidManifestMerger>` MSBuild property in their _.csproj_ files to take advantage of the latest approach [in Xamarin.Android SDK version 10.2 and higher](https://docs.microsoft.com/xamarin/android/release-notes/10/10.2#improved-android-manifest-merging), which is part of Visual Studio 2019 version 16.5 and higher and Visual Studio 2019 for Mac version 8.5 and higher.

**Comment by ncosentino** [comment]
I did as @stepheaw suggested and just updated all my firebase packages to the latest. From there, I uninstalled the manifest merger... and everything now works as I continue to add more nuget package dependencies.

So @brendanzagaeski I'd agree that the solution seems to just be "Update things and stop using the manifest merger"

**Comment by moljac** [comment]
closing this one
