### ISSUE TITLE
MLKit missing?

### ISSUE THREAD

**Issue by johnbmangold** [xamarin/XamarinComponents#932]
It seems that we have a bindings library for Firebase.ML, but no bindings library for Firebase.MLKit for Android at least. [Here is the iOS equivalent](https://www.nuget.org/packages/Xamarin.Firebase.iOS.MLKit.Vision/) of the package i'm looking for. Am i missing something or does Firebase.MLKit have a bindings library for iOS, but not Android?

**Comment by moljac** [comment]
Related PR

https://github.com/xamarin/XamarinComponents/pull/933

**Comment by vpenades** [comment]
@moljac We're looking forward the ML Kit for xamarin. But we're particularly interested in the [pose detection](https://developers.google.com/ml-kit/vision/pose-detection) component that has been recently added to ML Kit.

Since the pose detection component is not listed in the PR, I was wondering if it's going to be delayed for a future update, or if it's going to be available from the first version of the package.

**Comment by moljac** [comment]
published

closing this one
